apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvino-notebooks
  namespace: default
  labels:
    app.kubernetes.io/part-of: openvino_notebooks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: openvino_notebooks
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: openvino_notebooks
    spec:
      containers:
      - image: masanara/ov:2.1
        name: workload
#        env:
#        - name: TRANSFORMERS_CACHE
#          value: "/model/.cache/huggingface/hub"
        securityContext:
          runAsUser: 0
        resources:
          requests:
            cpu: 4
            memory: 14Gi
          limits:
            cpu: 4
            memory: 14Gi
            gpu.intel.com/i915: "1"
        volumeMounts:
        - name: model
          mountPath: /model
      serviceAccountName: default
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: model
---
apiVersion: v1
kind: Service
metadata:
  name: openvino-notebooks
  namespace: default
  labels:
    app.kubernetes.io/part-of: openvino_notebooks
spec:
  selector:
    app.kubernetes.io/part-of: openvino_notebooks
  type: NodePort
  ports:
  - targetPort: 8888
    port: 8888
    name: http
    nodePort: 30008

